### ISSUE TITLE
Support for minSdkVersion 15

### ISSUE THREAD

**Issue by pbednarz** [airbnb/epoxy#102]
Is there any particular reason why Epoxy supports SDK from API 16?
A lot of projects still have minSdkVersion set to 15, same for default project created in Android Studio.

**Comment by elihart** [comment]
When I first created Epoxy for our own app I used min 16 because that is what our app has. When I moved it to a library it wasn't a priority to change because there isn't a ton of usage below API 16.

I believe the min API could be much lower though since it just depends on the support library.

I'd welcome a PR to lower the min if anyone is interested and needs it!

**Comment by pbednarz** [comment]
That's totally fine. API 15 has very small impact on Android fragmentation right now. I was curious if there is  any edge case but Epoxy is working fine on min API 15 (at least in my project for now).
