### ISSUE TITLE
How to implement a repeating task to update the view?

### ISSUE THREAD

**Issue by MaximilianKeppeler** [airbnb/epoxy#1023]
Love Epoxy, thanks! 👍 

There's a thing I can't figure out:
I have a few model views inside my RecyclerView which need to display a timer and therefore need to be updated frequently and independently of my data model. 

**What's the best way to implement repeating view updates?**

What I tried so far:

**Implementing it into my EpoxyModelClass**
1. Scheduling a repeating task in my `EpoxyModelClass` 
2. At a data model change (e.g. pausing, resuming), the method `bind(holder: DataBindingHolder, previouslyBoundModel: EpoxyModel<*>)` is called.
3. That's where I update my TextView to display the new time.
Issue: The repeating task continues to run in the previouslyBoundModel, I'm not able to pause/ cancel it.

Is this attempt the right one? What I'm missing there then? 

**Implementing it into my EpoxyController**
1. Scheduling a repeating task in my EpoxyController implementation. When triggered, it calls `requestModelBuild().
2. I added an `EpoxyAttribute` which is always different and triggers a change.
3. It then calls the method `bind(holder: DataBindingHolder, previouslyBoundModel: EpoxyModel<*>)` 
4. I set the new timer time to the TextView. 
Issue: It's inefficient and triggers weird animations of items in the RecyclerView, since it's constantly busy rebuilding the models.

I use kapt and data binding. 
My model extens from DataBindingEpoxyModel.
My controller extens from AsyncEpoxyController.

Thanks in advance!

**Comment by elihart** [comment]
> Implementing it into my EpoxyModelClass

This would be the simplest and most efficient route. Start the timer in bind and and stop in in unbind. The timer logic should not live in your model, put it in your view (either a custom view or a view holder). That way you shouldn't have the previous model hold onto a reference

> Implementing it into my EpoxyController
This is also fine, and potentially the cleanest since it is more testable and mockable. There is a potential performance overhead like you mentioned though, which may or may not be a problem depending on how many models on screen and how often you update the timer (i am assuming you have async model building enabled, that would be required for this)

This should not trigger weird animations - the only reason I can think it would do that is if you don't have properly stable ids in your models. rebuilding models alone does not trigger item animations unless something in the views actually change. When the timer text changes only the existing view with the timer should be changed at all, and I don't think recyclerview would apply any animations

**Comment by MaximilianKeppeler** [comment]
My EpoxyModelClass previously directly extended from DataBindingEpoxyModel, so I had no ViewModel and therefore implemented the logic inside my EpoxyModelClass - which lead to the mentioned issues. I just created a ViewModel, created my binding from the itemView and added the logic. Now it works, understandably. Thank you very much!

**Comment by elihart** [comment]
ah yes, databinding would prevent you from having the required flexibility. glad you got it working
