### ISSUE TITLE
Prevent EpoxyRecyclerView from recycling certain ModelViews

### ISSUE THREAD

**Issue by oldsport76** [airbnb/epoxy#1064]
I'm using the `EpoxyRecyclerView` in a fragment holding many various types of `ModelViews`. One of the `ModelView` types is one containing a `WebView` that loads a website and adjusts that height of that view to its content. The amount of these `WebView` views is always finite and limited to only a few of them. I'd like to prevent the `RecyclerView` from recycling these `WebView` views, since their content reloads anytime the user scrolls them out and then back into view.

Normally, when writing a `RecyclerView.Adapter`, I would override the `getItemViewType()` function assigning a `viewType` to the `WebView` view and then override `onCreateViewHolder()` to provide the same `ViewHolder`.

When using an `EpoxyController`, I specify all the views declaratively and don't write the adapter. Is there are way to do this easily without having to write the adapter in the conventional way and still be able to use my current implementation with the `EpoxyController`?

**Comment by elihart** [comment]
Generally this is not something I would recommend, and it is working around the whole intention of RecyclerView. I see how it may be necessary for something like WebView though.

I believe you can achieve something like this by setting a custom item view type on your web view model. One way is to subclass the model and override `getViewType`, or you could make your model accept the view type as a parameter when constructing an instance.

This would allow you to specify a unique view type per model when you build them in your EpoxyController. The next step would be to make sure that the webview is not cleared, you can do this by essentially not implementing anything for `unbind` handling.

I believe with this approach that the view will technically be recycled, but it will work how you want because the custom view type will mean it will only ever be used with the same model again, and since nothing is cleared on unbind recycling it won't reset anything about it.

two notes though:
 - make sure that when it is rebound you handle the case that the view was previously set up, to avoid accidentaly resetting it
- the lack of unbind handling could potentially introduce leaks when the recyclerview is done being used, if you aren't careful to clear the view pool

**Comment by oldsport76** [comment]
Thanks for the hints. I'll try these approaches.

**Comment by oldsport76** [comment]
Everything described here works exactly as intended. Thanks!

**Comment by voneskuba** [comment]
But how can i use these approaches with `TypedEpoxyController` ? How can I handle unique view type? Because i got error `IllegalStateException: Could not find model for view type`. @elihart
