### ISSUE TITLE
Better support for item change animations

### ISSUE THREAD

**Issue by elihart** [airbnb/epoxy#185]
From an item animator we can delegate to each model to allow them to handle their change animations

**Comment by elihart** [comment]
@tschuchortdev let me know if you're still interested in putting up a PR for this

**Comment by tschuchortdev** [comment]
@elihart Yes I'm still working on it. I'd say the feature is about 80% finished. Initially I thought it would be already finished completely by now, but there were some complications. The A-key on my keyboard broke so I couldn't code for a few days. 

Currently I'm trying to implement the interrupted animation logic, which is relatively complex and thus porting it directly from the existing Kotlin code is really ugly due to Java's verbosity (it was borderline unreadable in Kotlin already).   

Is there decent documentation somewhere for 2.0 already? I really have no idea how this new controller stuff works, which makes it hard to test for me.

**Comment by elihart** [comment]
Oh boy, that is quite a complication. Glad your keyboard is fixed now. Too bad we can't fix Java so easily :(

I'm currently working on the documentation at https://github.com/airbnb/epoxy/wiki/Epoxy-Controller. I'm hoping to have that done today. Besides that the new sample shows example usage https://github.com/airbnb/epoxy/tree/2.0/epoxy-sample/src/main/java/com/airbnb/epoxy/sample

If you have any specific questions on it I'm happy to answer them here too. Thanks for continuing the work!

**Comment by sergeyfitis** [comment]
Any progress? Seems it would be useful for me.

**Comment by tschuchortdev** [comment]
@sergeyfitis: almost done. you can take a look at the PR, maybe you have some ideas how to improve it.

**Comment by elihart** [comment]
I don't think it makes sense for epoxy to try to tackle this anymore
