### ISSUE TITLE
Dealing with intentionally duplicated ids

### ISSUE THREAD

**Issue by geralt-encore** [airbnb/epoxy#196]
I have a screen which renders cart of products that user willing to purchase. The problem is that there might be duplicates if a user wants to buy two or more identical products (which is not the most common case, but perfectly legal). So what are the available options? Am I missing something? I haven't found any suitable solutions yet 😔

**Comment by elihart** [comment]
Yeah, we've run into similar issues, which is why I made the alternative ids options https://github.com/airbnb/epoxy/wiki/Epoxy-Models#model-ids. Not sure if you've seen that?

So you will have to make the model id by combining the product id with something else. One possibility is item count. If you have 2 of product X the model ids could be `model.id(productX.getid(), 1)`, `model.id(productX.getid(), 2)`. Another option could be to generate a UUID when the item is added to the cart, or possibly a string timestamp.

That's the general idea, it's up to you what other parameters you can use to generate the id. It is a little extra overhead unfortunately :( let me know if you have other ideas on how to approach this.

The other approach is a different UI design where products of the same type are grouped together :P

**Comment by geralt-encore** [comment]
Yeah, I've seen that but how diffing will work in that case? If I remove an item - positions of items next to him will change and I will end up with same items but with different ids. How Epoxy will handle that case?

I am also for the second approach but, unfortunately, it's not for me to decide 😔

**Comment by elihart** [comment]
if you build positions into the id then animations won't work as well. it might get confused between insertion/removal/move. It shouldn't crash though. If I imagine the standard cart design, the only change that can happen on the screen is a removal. Worst case is the animation would look wrong.

I think including position in the id is the worst option because of that, but also the easiest. If you can use some other metadata such as a UUID when added (I'm assuming the card data is just local on the device?) or `created_at` string that should work perfectly
