### ISSUE TITLE
Annotation processor cannot be found when the project is using Realm + Kotlin + Epoxy

### ISSUE THREAD

**Issue by kokeroulis** [airbnb/epoxy#225]
When i am trying to build epoxy inside to a project which has realm and kotlin the build fails.
The build fails with the following error. I have tried both versions of epoxy (2.0 & 2.1) same result.
I have created a repo which reproduces this issue
You can find the repository here https://github.com/kokeroulis/realm-book-example/tree/real_data

the branch is the real_data

> error: Annotation processor '__gen.AnnotationProcessorWrapper_devDebug_com_airbnb_epoxy_EpoxyProcessor' not found

**Comment by elihart** [comment]
thanks for reporting I'll check it out. I started looking into this yesterday right when you posted but then github went down... :P

**Comment by elihart** [comment]
@kokeroulis I noticed that the build.gradle file is using `apply plugin: 'com.neenbedankt.android-apt'` instead of `apply plugin: 'kotlin-kapt'

When I switched it though I ran into this problem https://stackoverflow.com/questions/44035504/how-to-use-data-binding-and-kotlin-in-android-studio-3-0-0 which seems like it may be fixed in Android studio 3.0 (didn't try that).

I'm not convinced this is an Epoxy issue. Can you make sure the build.gradle file is set up correctly for kotlin?

**Comment by kokeroulis** [comment]
@elihart yes you are correct. I don't think that this is an epoxy issue because upgrading to android gradle 3.0.0-alpha3 fixes the issue.

Also i have made some more experiments and i have find another workaround which works with android gradle plugin 2.3.0.

If you remove the ` apply plugin: 'com.neenbedankt.android-apt'` and without using the `kotlin-kapt` plugin, (so you just use the `kotlin-android` plugin) and upgrading the realm to version 3.3.1 then the issue goes away.

Which doesn't make a lot of sense.. 
But anyways, thanks

**Comment by geralt-encore** [comment]
@kokeroulis actually, there is an explanation for it. There is a difference between applying `kotlin-kapt` plugin and not doing it. Without plugin, the old version of `kapt` will be used and with plugin -
the newes`kapt3`, so it might worth reporting an issue to JetBrains guys if something doesn't work with `kapt3` =)
