### ISSUE TITLE
why do i set model hide or show ,but no any change

### ISSUE THREAD

**Issue by plmmanwu** [airbnb/epoxy#243]
sMsgTextModel_ = new MsgTextModel_().content(message.getMessageContent()).message(message).show(images.size() == 0 || images.size() > 2 || message.getMessageType() == ConstantUtils.VIDEO_MESSAGE);
        models.add(sMsgTextModel_);
        if (images.size() == 1) {
            sMsgTextModel_.hide();
//            addModel(new ImageItemModel_().context(context).picList(data).pic(data.get(i)).index(i).spanSize(spanSize))
            imgModels.add(new ImgLargeItemModel_().id(images.get(0).hashCode()).context(activity).picList(images).pic(images.get(0)));
        }

**Comment by elihart** [comment]
you need to notify the change as well. you need to either `notifyModelChanged(model)` or use the `showModel(...)` method which toggles visibility and notifies the change for you.

It is recommend to use the newer EpoxyController instead since it guarantees that all changes are notified automatically and it's impossible to have bugs like this
