### ISSUE TITLE
change layout programmatically

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#249]
How subclass of EpoxyModelGroup can programmatically change layout properties, as an example changes the background color of layout?

**Comment by elihart** [comment]
`EpoxyModelGroup` is itself just an epoxy model, so you can subclass and add EpoxyAttributes or otherwise modify it however you would a normal model.

I think the limiting thing here is that the root view isn't exposed. I think the easiest way to get around this is for me to make the root view accessible on the view holder class that `EpoxyModelGroup`, then you could override `bind` and do whatever you want to the view. I'll include that in the next update.

In the meantime you could use different layout xml's to change the background color, but that isn't the ideal approach and it would change the item view type so the view wouldn't be recycled.

**Comment by elihart** [comment]
I'll include this change in the upcoming release

**Comment by yumcoder-platform** [comment]
thanks a lot.

**Comment by yumcoder-platform** [comment]
1. **EpoxyModelGroup.bind() is final** and so can not override it and
2. when using EpoxyAttributes in such situation the following error is raised:

      **Error:(21, 120) error: EpoxyModelGroup.Holder has protected access in EpoxyModelGroup**

```
    protected class Holder extends EpoxyHolder {
        //...
    }
```

**Comment by elihart** [comment]
Ah, good points. I'll make this work

**Comment by elihart** [comment]
done https://github.com/airbnb/epoxy/pull/258

will be released soon
