### ISSUE TITLE
LayoutOverloads don't work for Kotlin custom views

### ISSUE THREAD

**Issue by bakua** [airbnb/epoxy#271]
Steps to reproduce:
 1. Create Java custom view.
 2. Set it up so it has layout overloads.
 3. Verify CustomViewModel_().withXxxLayout() method is generated.
 4. Convert custom view to Kotlin.
 5. Clean and rebuild project.
 6. CustomViewModel_().withXxxLayout() is not generated any more.

**Comment by elihart** [comment]
Thanks for reporting, and providing a clear repro.

I'm assuming the model generated from the kotlin view works fine in every other way?

**Comment by bakua** [comment]
Yes, so far no problems. We use it quite extensively.

**Comment by elihart** [comment]
Good to hear that at least :) sorry about the issue, I should be able to fix it soon

**Comment by elihart** [comment]
This is happening because we use a javac specific parser to get the layout names from the annotation.

Not sure how I'll fix this yet, but as a workaround you can use default layout names - https://github.com/airbnb/epoxy/wiki/Generating-Models-from-View-Annotations#default-layout-names

The code path this uses does not use the same resource parsing logic that is broken in kotlin, so it works fine (just tested it myself).

Since you already have the `PackageModelViewConfig` annotation set up for layout overloads, all you would need to do is remove the `defaultLayout` param from your `ModelView` annotations (assuming your layout files match the expected pattern).

We use this pattern ourselves and like it a lot. I hope this can help you work around the issue for now, let me know if you have questions

**Comment by elihart** [comment]
Sorry for the delay, I've spent some time looking into this and unfortunately cannot find a workaround. It seems to be a limitation of kotlin that the layout name is not preserved in the annotation processor.

The workaround I posted above works though, and seems like a fine option. I updated the wiki to reflect that https://github.com/airbnb/epoxy/wiki/Generating-Models-from-View-Annotations#layout-overloads-with-kotlin so hopefully that will work for everybody.

Sorry for the inconvenience
