### ISSUE TITLE
dynamic margin

### ISSUE THREAD

**Issue by yumcoder-platform** [airbnb/epoxy#337]
Is this correct to set margin in **bind** method or it better to pass into the holder and set it in **bindView**?

for example, in a list, we need TxetWiewModel with margin 8 dp and in another list, we need  TxetWiewModel with margin 16 dp

**Comment by elihart** [comment]
do you mean in the `onBind` callback that you can register on a model? That would work, but epoxy cannot diff that, so if you change the value dynamically for a given model id it won't update. If that isn't an issue then go ahead with that approach, otherwise you can pass the value to the holder and do it in bindView

We internally have a great library for styling views via Epoxy that we are hoping to open source soon, which would make cases like this much easier.

**Comment by yumcoder-platform** [comment]
thanks
