### ISSUE TITLE
Kotlin EpoxyModel Implementation

### ISSUE THREAD

**Issue by JohnKilcoyne** [airbnb/epoxy#354]
Hey Everyone, 

I'm hoping you all could clear up some discussion on my team about the proper use of EpoxyModel's and Kotlin. 

1. Can we use the EpoxyModel's ViewHolder implementation without using the annotations to generate the `Model`? if so, do we need to extend EpoxyModel and implement the equals and hashCode functions ourselves? 

2. Can we Implement EpoxyModel's with Kotlin `data class`'s? data classes generate their own subclass with an equals and hashCode function from the constructed parameters, but it doesn't seem to add the `super.equals(other)` by default so that may need to be overridden

Hopefully that makes sense. Thanks!

**Comment by elihart** [comment]
1. Yes, the annotations and generated code are purely boilerplate removal. You can accomplish the same thing manually exactly as you said. That's generally not recommended though as it is a lot of boilerplate to write and is error prone.

2. I've never tried using data classes as EpoxyModels, but I guess it would work. If the generated equals method doesn't call `super` then you are only missing out on the EpoxyModel#equals implementation check if the layout changed. If you don't use layout overloads this shouldn't be a necessary to check.

The generated models provide other nice things though, such as: onBind callback, better click listener support, and it implements `createNewHolder` for you.

Unless you are trying to avoid generating a model subclass, the approach I've found to be best for kotlin is to use a normal kotlin class with `@EpoxyAttribute` annotations

**Comment by JohnKilcoyne** [comment]
@elihart Thanks for the quick response! 

The issue we've found with using EpoxyModels as Kotlin data classes is, they will return false positives for the EpoxyModel's during an `equals()` check, if the models contains the same data but different EpoxyModel `id`s. The same is true for the `hashCode()` function. This is if you do not manually implement the equals/hashCode to use super. So are those functions are used only check if the layout has changed then?

**Comment by elihart** [comment]
The base `EpoxyModel#equals` method does check `id`,  but the differ already takes id into account when it compares models. It doesn't blindly compare models with `equals` to see if they are the same, it is aware of model id. For that reason I _believe_ it is fine to omit id from the equals check (let me know if you discover otherwise though). `id` is there mostly for correctness, since you're right that technically models with different ids should not be equal.

The other thing that is checked in the super call (besides layout) is `shown`. This is more of a legacy attribute that was used in the original EpoxyAdapter to hide models, it is not used in EpoxyController. Because of that it is also mostly fine to ignore it in the equals check - the exception is that `shown` can be used by models in an `EpoxyModelGroup`.

So besides the two caveats of dynamic layouts and using `shown` in a model group the `super.equals` calls is not critical.

I would love to see data classes integrate more smoothly with Epoxy. Please keep us all updated on how it works for you and if you discover any improved patterns :)

**Comment by JohnKilcoyne** [comment]
@elihart That's exactly what we wanted to know! We'll be sure to keep you updated on how it works and any potential problems/patterns we come up with. Thank you so much for all the help :)
