### ISSUE TITLE
Paging sits there continuously rebuilding model

### ISSUE THREAD

**Issue by chrisbanes** [airbnb/epoxy#363]
I'm see the following when trying to integrate `epoxy-paging`. It seems to be continuously rebuilding it's models with no end.

Here's a snippet from the log, but it carries on forever.
```
D  Models built: 0.615ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.506ms
D  Models built: 0.498ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.430ms
D  Models built: 0.469ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.495ms
D  Models built: 0.464ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.384ms
D  Models built: 0.467ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.386ms
D  Models built: 1.045ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.727ms
D  Models built: 0.673ms
D  Item range changed with payloads. Start: 0 Count: 21
D  Models diffed: 0.684ms
D  Models built: 0.638ms
```

Here's my [controller](https://github.com/chrisbanes/tivi/blob/cb/epoxy/app/src/main/java/me/banes/chris/tivi/util/EntryGridEpoxyController.kt), [LivePagedListProvider](https://github.com/chrisbanes/tivi/blob/cb/epoxy/app/src/main/java/me/banes/chris/tivi/util/EntryViewModel.kt#L45). It happens with placeholders on and off.

Any ideas?

**Comment by elihart** [comment]
Thanks for reporting, and for the detailed example.

The differ is reporting that 21 models changed at the start of the list though, so that is a clue that your models have something changing in their state. The most common cause of this is some sort of listener changing.

in your model I see
```
@EpoxyAttribute var clickListener: View.OnClickListener? = null
```

which is most likely the issue.

you can use `@EpoxyAttribute(Option.DoNotHash)`

let me know if this fixes it. In general I recommend custom views with @ModelView since that does a better job validating common errors like this, but I understand when a viewholder is a simpler approach

**Comment by chrisbanes** [comment]
That worked. Thanks!
