### ISSUE TITLE
Different sized model groups

### ISSUE THREAD

**Issue by olLenz** [airbnb/epoxy#384]
Model groups is a nice feature of epoxy! But sadly I can't use it in my current use case:

I have an indefinite amount of groups (each group is shown on one card view) and each group has an indefinite amount of items. 

When I currently want to show different amounts of items on the card views I need to hide the unneeded items or use a new layout file for each group. But if there is an indefinite amount of items and groups I can't use one of these options.

Is there an option to allow groups with different sizes ?

**Comment by elihart** [comment]
Thanks for posting, this is an unfortunate limitation that I would really like to support, but it is not possible at the moment.

This issue is similar to https://github.com/airbnb/epoxy/issues/289, they share the same root issue and would both be solved by this feature.

I've thought a fair amount about this and believe it should be possible. I haven't had time to focus on it, but would like to in the future, although that might not be soon. If anyone wants to tackle this I'm happy to get them started.

**Comment by elihart** [comment]
This is finally fixed with https://github.com/airbnb/epoxy/pull/657 !
