### ISSUE TITLE
How to get the actual ViewHolder outside the Model?

### ISSUE THREAD

**Issue by littleGnAl** [airbnb/epoxy#409]
Hi, @elihart, I encountered a similar problem #218, I have an model that with a custom view and I should use the custom view to do some animation:
```java
@EpoxyModelClass(layout = ...)
public abstract class HSICircleHeaderModel extends
    EpoxyModelWithHolder<HSICircleHeaderModel.HSICircleHeaderHolder> {

  @Override
  public void bind(HSICircleHeaderHolder holder) {
    holder.circleView.updateValue(...);
  }

  public static class HSICircleHeaderHolder extends EpoxyHolder {

    @BindView(...) HealthSignInExerciseDietProgressView circleView;

    @Override
    protected void bindView(View itemView) {
      ButterKnife.bind(this, itemView);
    }
  }
}
```
And I want to use the `RecyclerView.ItemAnimator` to implement the `boolean animateAdd(...)` and `animateChange(...)` that show the deferent animation. But the epoxy wrapper the `HSICircleHeaderModel` and the `HSICircleHeaderHolder` into EpoxyViewHolder, and the `Object objectToBind()` is `protected` so I can't get the actual `HSICircleHeaderHolder`.
 Is there any good solution?

**Comment by elihart** [comment]
I see, the only solution would be to change that method to be public, or to create your animator in the same package.

I guess public would be ok, but it's something I prefer not to expose - since the holder is not typed its not really a safe thing to just expose the Object.

you could also change to not use a holder pattern, and just use a custom view that you bind directly to (maybe try @ModelProp). then you can get the itemView off of the ViewHolder like normal

**Comment by littleGnAl** [comment]
Thanks you answer @elihart, I solved the problem by change the animation flag multi times, I'll try the `@ModelView` , and it seems a very good feature.
Thanks this awesome library!!!
