### ISSUE TITLE
[Paris] No default style for view leads to IllegalStateException

### ISSUE THREAD

**Issue by reavcn** [airbnb/epoxy#434]
Hi, 

this is more of a question, as the causes that lead to the exception are well documented [here](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)) under the "Recycling Views" paragraph.

In the last few months we've been looking for an easy way to set styles/attrs to our views/models and the Paris integration just feels like a godsend!

There's something we're missing though. 

Our typical view (annotated with @ ModelView) is a custom view which usually extends either ConstraintLayout or LinearLayout. More importantly, we never apply styles from styles.xml to it, so we don't really have a "default" one. 
We just want to set different paddings each time.

The [documentation](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)) says:

> By default the view's default style is used, per Paris's default rules.

If no default style is provided, Paris is using a DEFAULT_PARIS_STYLE, which is basically an empty style generated this way:

```java
private static final Style DEFAULT_PARIS_STYLE = new MyViewStyleApplier.StyleBuilder().addDefault().build();
```

The following code leads to an IllegalStateException thrown by the assertSameAttributes() method.

```kotlin
myRecyclerView.withModels {
        myView {
                id(MyView.TAG)
                text(headerText)
                styleBuilder {   builder ->
                        builder.paddingBottomDp(10)
                }
        }
}
```

```
java.lang.IllegalStateException: MyViewModel_ model at position 0 has an invalid style:
The MyView style "EmptyStyle" is missing the following attributes:
✕ paddingBottom
It must declare the same attributes as the following styles:
a_programmatic_StyleBuilder
```

On the other hand, if I set a @ Style in MyView with option (isDefault = true) and then set paddings using styleBuilder, then everything works flawlessly.

So, my question is: is there any way we can just build the style using styleBuilder and avoid linking a default @ Style inside the view?

**Comment by elihart** [comment]
you're right about everything you said, and the reason a default style is needed is basically to help everyone prevent bugs. As you noted, Paris's default style is empty because it can't know about what attributes are applied in your xml. Say you applied a certain padding in the original xml layout, then overrode that in the epoxy model with a style builder - if you built some `myView` models with a stylebuilder and some without epoxy would recycle views between the models, but there would be a bug because you end up with three cases

1. original view from xml with some unknown settings
2. model with stylebuilder forces some settings via paris
3. recycled view with model with no stylebuilder inherits from either 1 or 2, so actual padding is unknown

This is what we mean when we say recycling breaks, and is why we have the check, otherwise very annoying and hard to debug issues would pop up.

It is annoying to define default styles for all views, and we are trying to provide some tools to make the process easier.

For one, check out https://github.com/airbnb/paris/pull/26 which will hopefully be released soon. This reduces the boiler plate for declaring a style to just
```
@Style
val DEFAULT_STYLE = styleMyView {
   paddingBottomDp(10)
}
```

a remaining annoyance is if your default style has 0 padding and you don't want to declare that a bunch of times for all views in order to be able to override it in epoxy models. How we improve that case is by having a base view class that we extend our custom views from. That view can set default padding values, background, everything you want, etc. 

```
@Style
val BASE_STYLE = styleMyBaseView {
   paddingBottomDp(10)
paddingTopDp(10)
paddingLeftDp(10)
...
}
```

then in subclasses you can inherit the defaults with 
```
@Style
val defaultStyle = styleMyView {  add(BASE_STYLE) }
```

Then you can override any values set in the base style in your epoxy models.

This still requires you to add that one line style to all your models, but its not too bad. It just occurred to me that maybe we could have Paris make a view's default style inherit from it's superclass if it doesn't otherwise define one. Thoughts @ngsilverman ?

**Comment by ngsilverman** [comment]
I still don't think that views should _automatically_ inherit linked styles from their parents because styles might not be designed for inheritance. We could make it possible to enable that behavior though:
```kotlin
// Inherits styles from its direct parent
@Styleable(inheritStyles = true)
public class MyView ...
```
Or the other way around:
```kotlin
// All subclasses will inherit styles from this class
@Styleable(openStyles = true)
public class MyBaseView ...
```
This could also be done on a per style basis:
```kotlin
@Style(open = true)
val defaultStyle = ...
```
And/or we could create this shortcut:
```kotlin
@Style
val defaultStyle = myViewStyle { addParentDefault() }
```
I like the `openStyles`/`open` option best because it's the minimal code change: set it on the base class and you're set. It also lets view types decide for themselves whether their styles are meant to be inherited.

**Comment by reavcn** [comment]
Thanks a lot !!! You've been very helpful and crystal-clear. 
Of course my intent was not to say that your approach was incorrect, but rather to understand whether I fully got the idea behind the recycling breaks.

@elihart Sure, I'll be checking out https://github.com/airbnb/paris/pull/26 for updates! 
For now, I'll define a @ Style(isDefault = true) with all the needed attributes and I'll override values for them if I need to, similarly to what you said.

I also agree with @ngsilverman that views shouldn't automatically inherit styles and I like the proposals, especially the 3rd one ("per style basis").

Many thanks again, I really appreciate your support

**Comment by ngsilverman** [comment]
@reavcn did you mean https://github.com/airbnb/paris/issues/49 for updates? https://github.com/airbnb/paris/pull/26 is a merged PR. Also if you're interested in contributing that change I'd be happy to provide some guidance to help get you started. It shouldn't be too difficult.

**Comment by reavcn** [comment]
@ngsilverman yes, my bad! I meant https://github.com/airbnb/paris/issues/49 

I'd be glad to contribute, but I'm relatively new to Android and still don't feel quite confident, so I'll have to pass for now, but thanks!

**Comment by elihart** [comment]
The next Paris release will improve default style handling, and will have kotlin functions for declaring default styles, which will make this easier and clearer.

**Comment by setyongr** [comment]
Hi, how to add default style in kotlin? i always getting compilation error.
I try add it as an attribute and companion object with `@JvmStatic` but doesn't work
