### ISSUE TITLE
Studio Layout Preview cannot find class

### ISSUE THREAD

**Issue by athornz** [airbnb/epoxy#454]
Hi,

I'm attempting to use a EpoxyRecyclerView in a layout but the Android Studio Layout Editor is unable to preview the layout due to the following error:

```
The following classes could not be found:
- com.airbnb.epoxy.LinearLayoutManager
```

Running the app is fine, so this is only a layout preview issue. 

I've used Epoxy fine in other projects, so I'm wondering if this may be due to the fact that this layout is inside a library module rather than an app module.

**Comment by josephyanks** [comment]
Not sure without seeing code, but references to the layout manager should be android.support.v7.widget.LinearLayoutManager

**Comment by athornz** [comment]
I'm actually not referencing that epoxy layout manager at all, just simply declaring an epoxy RecyclerView in xml.

**Comment by josephyanks** [comment]
It's not finding it because that class doesn't exist https://github.com/airbnb/epoxy/search?q=layoutmanager&type=Code which points to probably an invalid import or maybe an invalid tools:layoutManager declaration? App module vs library module shouldn't matter so long as the imports for epoxy and support lib are present. If you check the imports (in java/kotlin as well as xml) and your gradle, I'd suggest posting code to try to narrow it down. If you replace the EpoxyRecyclerView with a normal recycler view, does it compile?

**Comment by athornz** [comment]
Hmm the plot thickens. It compiles fine with just a normal RecyclerView. 

Perhaps this is a studio issue (I'm using 3.2 beta). I'll try investigate some more.

**Comment by athornz** [comment]
I came across this in another project I'm working on as well. The common denominator is Android Studio 3.2 beta.

I haven't had a chance to create a test project but I will when I get time.

**Comment by athornz** [comment]
I've narrowed this down to an issue with Android Studio 3.2 only. 

Android Bug Report here: https://issuetracker.google.com/issues/110946871

**Comment by RoudyK** [comment]
If you're using a canary/beta version 3.2+, the below "hack" works for me for the time being, it's ugly but defining the layout manager in xml gets rid of this error and the preview works fine, for ex:
`app:layoutManager="android.support.v7.widget.LinearLayoutManager"`
