### ISSUE TITLE
How to set custom LayoutManager/ItemDecoration for Carousel?

### ISSUE THREAD

**Issue by Xset-s** [airbnb/epoxy#486]
I have code:
```
// EpoxyModelGroup
companion object {
	fun buildModels(models: List<SampleModel>): MutableList<EpoxyModel<*>> {
		val models = mutableListOf<EpoxyModel<*>>()

		models.add(HorizontalCarouselModel_()
			.id("subscriptions")
			.withModelsFrom(models) {
				SampleModel_()
				...
			}
		)
		
		...

		return models
	}
}
```

Why i must create HorizontalCarouselModel, VerticalCarouselModel...?
Why you can't create 1 flexible model?

Smth like that:

```
CarouselModel_()
	.id(...)
	.layoutManager(...)
	.customDecoration(...)
```

**Comment by Xset-s** [comment]
Sorry :c
I didn't read the whole wiki (ModelProp)...

```
@ModelProp(ModelProp.Option.DoNotHash)
fun addCustomItemDecoration(decorationBuilder: (context: Context) -> ItemDecoration) {
	addItemDecoration(decorationBuilder(context))
}
```
```

HorizontalCarouselModel_()
	.id("subscriptions")
	.addCustomItemDecoration {
		Decoration.Builder(it)
				.orientation(Decoration.VERTICAL)
				.rightDistance(16f)
				.build()
	}
	...
```

👍

**Comment by elihart** [comment]
glad you got it figured out.

The reason we don't set layoutmanager as a prop is because it doesn't work well to recycle it between carousels. You also can't use the same one for each model, and you don't want to create a layout manager for each of your potential hundreds of models.

what you could do is create a data class to define settings for your layout manager, and update or create a new layout manager in the carousel on bind based on that
