### ISSUE TITLE
Support for setting the item spacing of a carousel

### ISSUE THREAD

**Issue by pwillmann** [airbnb/epoxy#514]
Currently it is possible to set the Padding of a carousel via a resource or dp while the item spacing can only be set as part of the `Carousel.Padding` object and only directly in pixels. Would be great to be able to set the item spacing as dp or resource too.

As i understand it's only a matter of adding a `@ModelProp` annotation right?

**Comment by elihart** [comment]
Yep, I've thought about this too. I left it off because it adds a lot of extra size to the Padding class. I would be open to updating the class to allow it though, maybe something like `Padding.dp(4)`. or `Padding.resource(R.dimen.foo)`

You could add a new property with `@ModelProp`, but you'd have to be careful with that because having two @ModelProp setting the same underlying value can conflict.
