### ISSUE TITLE
The most efficient way to create models with `Kotlin`

### ISSUE THREAD

**Issue by qbait** [airbnb/epoxy#559]
Great that you are flexible, but which method do you recommend for creating models with `Kotlin` / which one do you use for AirBnb app?

I like `Android Databinding` conceptually, cause it cuts so much boilerplate, but debugging, build times and tooling were quite sad for a bigger project in the past. Guess, it's the same when used with Epoxy?

**Comment by elihart** [comment]
We use the custom view approach with @ModelView, but we have quite a bit of  separate tooling built around that that makes it very helpful. I think the viewholder approach can be fine for simple views.

Databinding is fine, but like you said, it has downsides. Each approach has pros and cons, we don't make a blanket recommendation because every app has its own use cases.
