### ISSUE TITLE
[Question] Best practices for fragments

### ISSUE THREAD

**Issue by pjr0001** [airbnb/epoxy#606]
Hi, I have a few questions regarding the use of fragments and epoxy. Admittedly, I'm not the most experienced android dev. Feel free to point me towards any docs if this has already been covered somewhere.

I recently changed one of my activities into a fragment. After doing this, I started to have some issues. In general, it'd be really helpful if there was an example of using epoxy with a fragment (all of the examples seem to use activities). 

Using activities: I was using EpoxyRecyclerView.withModels inside of Activity#onCreate to avoid setting up a controller class. This worked great.

Using Fragments + android jetpack navigation: Here's where I have some questions:

- Given a fragment class. Is it possible to still use EpoxyRecyclerView.withModels? 
- If so, what lifecycle method should this go in? 
    - onCreateView: I don't think this is right, since it's ran every time we navigate to/from this fragment?
    - onCreate: seems more appropriate, but there isn't a reference to the recycler view yet, so I'm not sure how to call recyclerView.withModels.
- Using Fragment#onCreateView + EpoxyRecyclerView.withModels + model groups, I am getting an error "The number of models used in this group has changed. The model count must remain constant if the same layout resource is used."

```
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?,
                              savedInstanceState: Bundle?): View? {
        // Inflate the layout for this fragment
        val view = inflater.inflate(R.layout.fragment_me, container, false)
        view.me_recycler_view.withModels {
            val tasks : List<EpoxyModel<*>> = listOf(

                    IconTableRowBindingModel_()

                            .id("steps")
                            .title("My Tasks")
                            .icon(R.drawable.ic_check)
                            .color(R.color.tasks_icon)
                            .clickListener { v ->
                                val intent = Intent(v.context, StepsIndexActivity::class.java)
                                v.context.startActivity(intent)
                            }
            )
            EpoxyModelGroup(R.layout.card_group, money).addTo(this)
        }
        return view
}
```

Bonus question:

- Am I able to use the paris integration if I'm using auto generated models (i.e. view_holder_*)?

**Comment by elihart** [comment]
Fragments shouldn't work any differently than activities with Epoxy, the only thing to be aware of is lifecycle, like you mentioned.

`onCreateView` is a fine time to initialize the models, or you could do a similar callback like `onViewCreated` or `onActivityCreated`. You do need to define the models again when the view is created, there is nothing wrong with that.

The error `The number of models used in this group has changed` is unrelated to fragment usage, although with fragments you are sharing a viewpool, so it might make it happen more often. You _can't_ use a variable number of models inside a group, it needs to be static. There are several issues about this with more information.

And yes! You can use Paris in that case

**Comment by pjr0001** [comment]
@elihart - Thank you for the quick response. Two quick follow up questions:

I some a master-detail fragments setup using android's new navigation framework. Consider this scenario:
- User navigates to detailFragmentA,
- go back
- User navigates to detailFragmentB (same fragment, populated with different data), using android's Navigation#navigate.

I get the "number of models changed" error.  How can I ensure that everything epoxy-wise is reset/cleared upon navigating away from detailFragmentA.
(I read and followed: https://github.com/airbnb/epoxy/wiki/Avoiding-Memory-Leaks but using setAdapter(null) inside onDestroyView, but that didn't seem to resolve the issue.)

- Regarding paris: If I'm using the view_holder* xml pattern (I'm not creating a @ModelView class), how do I annotate those xml views as @Styleable, making the styleBuilder function available.

Thanks again for the help!

**Comment by elihart** [comment]
You don't have to do anything special when navigating away from a fragment or sharing fragments. As long as your models correctly clean up their views in unbind/recycle then you're fine. That cleanup is necessary for a single recyclerview and fragment as well, so multiple fragments doesn't change anything.

Epoxy automatically has the fragments share a viewpool, which is a good thing, because when you open a new details fragment the views don't have to be created again so it loads faster.

The problem you're facing is specific to EpoxyModelGroup, and has nothing to do with different fragments, you could run into the same issue within the same recyclerview if you model count changed. This is just a limitation with the current implementation of the model group - the model count can't change across different usages. So you can't add two models to the group in one place and three models to it in another, because they will be recycled between each other and crash.

I'd like to fix it one day when I get time, but for now you can make it work by forcing a different view type. The view type by default is the layout xml file, so if you use a different view type for different model counts it should work
```
protected int getViewType() {
    return getLayout() + 31 * models.size();
  }
```

that's just an example - you basically want a good way of coming up with a unique view type based on the model count and layout, while avoiding collisions with other layout view types. You could make the result negative to avoid collisions with other layout types.


With Paris, styling manual models is only possible if the view type of the model is a custom view with the `@Styleable` annotation. You don't need to use `ModelView`, but it does need to be a custom view.

I suppose it would be a reasonable feature request to generate the styleable methods by default if Paris is in the classpath
