### ISSUE TITLE
How to test controllers

### ISSUE THREAD

**Issue by aahlenst** [airbnb/epoxy#631]
Could you expand the docs with some sample code on how to test EpoxyControllers? In my case, I'm most interested to perform assertions on the rendered views, e.g. is a button visible/clickable or not because that changes from item to item. Or should I do something else?

The best what I've come up so far with is to inflate the `EpoxyRecyclerView` with Robolectric and then to perform assertions using Espresso. The problem is that my items are off the screen and therefore I cannot perform click operations.

```
@RunWith(AndroidJUnit4::class)
class EpoxyTest {

    @get:Rule
    val rule = IntentsTestRule<DummyActivity>(DummyActivity::class.java)

    @Test
    fun epoxyTest() {
        val view = rule.activity.findViewById<EpoxyRecyclerView>(R.id.recyclerView)
        val controller = DummyController()
        view.setController(controller)
        controller.setData(DummyData())
        
        onView(withId(R.id.name)).check(matches(withText("Some name")))
        onView(withId(R.id.description)).check(matches(withText("Lorem ipsum")))
        onView(withId(R.id.email)).perform(click())
    }
}
```

Maybe I'm doing it totally wrong, so any hints would be greatly appreciated.

**Comment by elihart** [comment]
Espresso offers interactions for RecyclerView: https://developer.android.com/training/testing/espresso/lists#recycler-view-list-items

I think it would be best to use those.

I think in your case Epoxy isn't any different from testing a normal RecyclerView, since at the heart of it it's just a normal RecyclerView adapter

**Comment by aahlenst** [comment]
Thanks for your answer. I saw those, they don't seem to work:

```
onView(ViewMatchers.withId(R.id.recyclerView))
    .perform(RecyclerViewActions.scrollToPosition<RecyclerView.ViewHolder>(0))
onView(withId(R.id.email)).perform(click())
```

Results in the following exception:

```
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
at least 90 percent of the view's area is displayed to the user.
Target view: "AppCompatImageView{id=2131230840, res-name=email, visibility=VISIBLE, width=24, height=24, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@63f40ca0, tag=null, root-is-layout-requested=false, has-input-connection=false, x=208.0, y=-3.0}"
```

Maybe it's a problem with Robolectric. Which brings me back to my central question: Is that the best way to test `EpoxyControllers` and model binding or is there a better one?

**Comment by elihart** [comment]
I don't personally have much experience unit testing Epoxy controllers - the approach I am taking is to screenshot the whole activity to avoid manually writing test code for everything. Maybe others that have written tests can chime in?

I would think that Espresso should just work, I personally wouldn't trust robolectric and would run the test on an emulator with espresso to make sure there are no issues caused by mocking..

If you really want a more pure unit test, what you could maybe do is take an adapter and call `onCreateViewHolder` and `onBindViewHolder` manually for each position/model. Then get the resulting view off the viewholder and make whatever assertions you want on it, possibly forcing it to layout in whatever size you want.

I could imagine a small test harness that takes an adapter and a list of lambda assertions about each position

**Comment by aahlenst** [comment]
Thanks a lot for the guidance.

I've settled for Espresso on a real device/emulator (for invisible things) + screenshot testing. The exceptions vanished as soon as I ran the tests on the device.
