### ISSUE TITLE
Build files conflict with Glide

### ISSUE THREAD

**Issue by nikhilpanju** [airbnb/epoxy#710]
We try and use `GlideApp.with(fragment)` as much as we can. While trying to implement Epoxy, we ran into an issue though.
```kotlin
@ModelProp(options = [ModelProp.Option.DoNotHash])
lateinit var glideRequest: GlideRequests

@AfterPropsSet
fun afterPropsSet() {
    glideRequest.load(url).into(imageView)
}
@OnViewRecycled
fun onViewRecycled() {
    glideRequest.clear(imageView)
    imageView.setImageDrawable(null)
}
```
Most of our custom views have this so that we can use the GlideRequest with the fragment lifecycle in our views.

The issue here is, Glide also generates the GlideRequests file while building the project from the GlideModule of our app
```java
@GlideModule
class MyGlideModule : AppGlideModule()
```

The generated EpoxyModels don't have the proper generated code or imports to set the gliderequests dynamically since glide and epoxy both generate the files when building the project and afaik the order of annotation processing also cannot be preset to generate Glide files first then Epoxy.

The only option we have is to go back to using `GlideApp.with(context/activity)` instead of fragment. Is there any other way?
Thanks

**Comment by elihart** [comment]
I think you need to enable the kapt setting to use stubs

**Comment by nikhilpanju** [comment]
'kapt { generateStubs = true }` is already present in my build.gradle file. It still throws up an error. Only way I can do it right now is either
1) Sacrifice the custom glide module and just use plain old `Glide.with(fragment)` which returns a `RequestManager` object (part of the Glide APIs)
or
2) Have some tightly coupled way of casting the custom view context to the container activity and implement some logic in the activity to find the current fragment and return `GlideApp.with(fragment)` from there

Is there a better solution?

**Comment by elihart** [comment]
What is the error you are seeing exactly? You originally just said `generated EpoxyModels don't have the proper generated code or imports` so it isn't clear what is actually happening in the generation.

Taking a step back though, this seems unnecessarily complex. You said this is `so that we can use the GlideRequest with the fragment lifecycle in our views.`, but views in a RecyclerView already have a narrower lifecycle than the fragment. You are clearing the request in `@OnViewRecycled`, so as long as the recyclerview is cleared when the fragment view is destroyed all the requests will also be canceled. This makes it fine to use `GlideApp.with(context/activity)` - this is what we do in our app and it works great.

**Comment by nikhilpanju** [comment]
Yes, I agree. After looking at various ways to do it, it added unnecessary complexity.

`GlideApp.with(context/activity)` works just fine. Thank you
