### ISSUE TITLE
EpoxyRecyclerView didn't get updates until some delay

### ISSUE THREAD

**Issue by diousk** [airbnb/epoxy#763]
I have a frequently changed list(mostly just insert data) and I made the updates between each TypedEpoxyController.setData() at least 450ms. 

So the buildModels method is triggered at least 450ms interval too.

The buildModels() is called correctly at the right time,
**but sometimes the recycler view on the UI won't get updates until some delay**

here is the log, I print the last item of the list inside buildModels()
and I also print the log when bind() method gets called inside my EpoxyModelWithHolder
```
2019-06-11 23:25:56.630 12374-12374 buildModels() last item = DataModel(id=1560266745502)
2019-06-11 23:25:57.081 12374-12374 buildModels() last item = DataModel(id=1560266746782)
2019-06-11 23:25:57.101 12374-12374 bind() dataModel = DataModel(id=1560266746782)
2019-06-11 23:25:57.105 12374-12374 bind() dataModel = DataModel(id=1560266745502)
```

As the log shows, the data is not duplicated and **the bind() method for the two holders gets called only when the second buildModels() is triggered**
and I just take the id from DataModel to set into id() of holder

I want the dataModel to be bound to holder every time buildModels() is triggered 

How do I solve it (to remove the delay/debounce)?

epoxy version: 3.4.2

**Comment by elihart** [comment]
Calling `setData` triggers a call to buildModels, which in turn calls `requestDelayedModelBuild(0)`

This code does
```
public synchronized void requestDelayedModelBuild(int delayMs) {
    if (isBuildingModels()) {
      throw new IllegalEpoxyUsage(
          "Cannot call `requestDelayedModelBuild` from inside `buildModels`");
    }

    if (requestedModelBuildType == RequestedModelBuildType.DELAYED) {
      cancelPendingModelBuild();
    } else if (requestedModelBuildType == RequestedModelBuildType.NEXT_FRAME) {
      return;
    }

    requestedModelBuildType =
        delayMs == 0 ? RequestedModelBuildType.NEXT_FRAME : RequestedModelBuildType.DELAYED;

    modelBuildHandler.postDelayed(buildModelsRunnable, delayMs);
  }
```

So you can see that the call to build models is always posted to the next frame. The only reason I can think of that your call is delayed by a few hundred ms is that your app is doing too much work on the UI thread so that it delays the model building.

The model building happens as soon as possible after you call it, if the second call gets combined with the first it is only because the model build hasn't had a chance to happen yet. There is no fix to that besides making your app run faster.

**Comment by diousk** [comment]
After some investigation, I found that the items are actually insert into the recyclerview.
But it just not scroll down to the newest one automatically. 
The related issue #648 had explained about this. I'll close this issue.

Thanks for the help
