### ISSUE TITLE
Carousel building with Kotlin DSL

### ISSUE THREAD

**Issue by eboudrant** [airbnb/epoxy#847]
Regarding the nice Kotlin  DSL we have to build model, we still need to use the model constructor for carousels (ie: `PhotoViewModel_()`) : 
```
fun buildModels() {

   val photoModels = mutableListOf<PhotoViewModel_>()
   photos.forEach {
      photoModels.add(PhotoViewModel_().apply {
        id(photo.id())
        url(photo.url))
      }
   }

   carousel {
        id("carousel")
        numViewsToShowOnScreen(5)
        models(photoModels)
    }
}
```

Does a DSL for building carousel was ever considered or is there a known limitation? This could be much more simple to write/read : 

```
fun buildModels() {
   carousel {
        id("carousel")
        numViewsToShowOnScreen(5)
        photos.forEach {
            photoView {
                 id(photo.id())
                 url(photo.url))
            }
        }
    }
}
```

**Comment by elihart** [comment]
Yes, this would be ideal and has been brought up before. It is possible - the problem is that the extension function to create the model uses an EpoxyController as a receiver, so we need a syntax that changes the receiver to be a separate EpoxyController that we then pull the models off of.

It would be more feasible to do something like this
```
   carousel {
        id("carousel")
        numViewsToShowOnScreen(5)
        models(buildModels {
           photos.forEach {
             photoView {
                 id(photo.id())
                 url(photo.url))
            }
        }
      }
    }
```

This allows us to change the receiver. The only way to do it in your example would be to create a special extension function `carousel` that uses that receiver. This would conflict with the default `carousel` unless the annotation processor was able to replace the default, which is possible but just gets more complex

**Comment by elihart** [comment]
I think https://github.com/airbnb/epoxy/pull/850 accomplishes the syntax you demonstrated.

It should work - tasks left are
- Make sure it doesn't break existing usages
- Decide whether to ship with a different function name than `carousel`, or update our code replace the generated carousel function with this custom one somehow
- Think about providing an easy pattern for users with custom carousels (or other nested models, like possibly EpoxyModelGroup) to also apply this approach

**Comment by eboudrant** [comment]
Nice, I will check it out !

**Comment by apramana** [comment]
Hi @elihart - are there any plans to revive this improvement? Also, would it make sense for Carousel to use `withModels` with `@ModelProp` so that callbacks are used through the entire chain? Or maybe there's a technical constraint I'm missing here.

**Comment by elihart** [comment]
@apramana I had forgotten about this. if you would like to continue work on my PR (needs testing, documentation, polish, etc) then feel free to fork that branch
