### ISSUE TITLE
OnModelClickListener  onClick() ，model not up-to-date

### ISSUE THREAD

**Issue by turingking** [airbnb/epoxy#877]
```java
ItemCommentBindingModel_().id(item.id)
            .comment(item) //hasCode = 1576
            .listener {
               model, parentView, clickedView, position ->{
               var comment = model.comment() //hasCode = 1555
              }
               
          }
```
Why is the comment object in the model not updated? 
How can I get the latest value?

**Comment by turingking** [comment]
I found that if the comment is a kotlin data class, it can be updated immediately.

**Comment by walker622** [comment]
Because under the hood epoxy using [DiffUtil.Callback](https://developer.android.com/reference/android/support/v7/util/DiffUtil.Callback), which has two methods. 
1. `areContentsTheSame` has the responsibility to check items type. If it returns false, it means that we are comparing items with a different view holder type, otherwise, look below.
2. `areItemsTheSame` has the responsibility to check "Are items have the same rendering object (view object)?", only for those items which have returned true in the first method (above). So if it returns true, it means that this view holder does not need to call bind method, because it has the latest view object, otherwise, it calls bind method.

So conclusion, your view objects (models, pojo or whatever) must override hashCode and equals. Method `hashCode` is for representing a combined integer hash value of your internal data values, and `equals` is for checking equality.
As we know, Koltin automatically overrides `hashCode` and `equals` for data class.

**Comment by turingking** [comment]
@walker622 thank you very much
