### ISSUE TITLE
4.0.0-beta1 doesn't compile if controller/model are written in Kotlin

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#982]
Upgraded from 3.11.0 to 4.0.0-beta1 and now my code won't compile.

Have about 10 errors that look like this in my build output:

```
  controller.headerEpoxyModel = new (@org.jetbrains.annotations.Nullable :: HeaderEpoxyModel_)();
```

If I look inside the generated code in `MyController_EpoxyHelper`

```
  @Override
  public void resetAutoModels() {
    validateModelsHaveNotChanged();
    controller.headerEpoxyModel = new (@org.jetbrains.annotations.NotNull :: HeaderEpoxyModel_)();
    controller.headerEpoxyModel.id(-1);
    setControllerToStageTo(controller.headerEpoxyModel, controller);
    saveModelsForNextValidation();
  }
```

I took a look at some other generated controllers (because they seem to compile just fine) and it seems like my java codebase works just fine, but if I have a controller + model that uses kotlin then I get the issue. I'm not sure if it's explicitly the model, or the controller or both as my project is split right down the middle and I have java epoxy controllers and models, then I have kotlin epoxy controllers and models. My guess is that just some of the kotlin generated code with nullability aren't taken into account?

**Comment by elihart** [comment]
Thanks for reporting. There was actually some change to the controller processor to support incremental that I forgot to mention in the release notes.

For the processor to correctly recognize the model it must be either in a different module, or within the same package of the same module.

Let me know if this is the case for you and whether this might be a separate issue.

By the way, it is not recommended to use AutoModels with kotlin. AutoModels are more of a legacy thing made to have less verbose java code.

**Comment by ColtonIdle** [comment]
>For the processor to correctly recognize the model it must be either in a different module, or within the same package of the same module.

Different module in relation to what? The controller?

If so, I can definitely make sure that my model and controller are in the same package as I don't have a multi-module app.

> By the way, it is not recommended to use AutoModels with kotlin. AutoModels are more of a legacy thing made to have less verbose java code.

I should be able to change that. What's the recommended solution?

**Comment by elihart** [comment]
yes, the controller and model either must be in a different module or be in the same package of the same module. So yes, move them to the same package and let me know if that fixes the issue.

The recommended approach is to write your controller in Kotlin and use the generated kotlin extension functions to create models

```
buildModels() {
  myView {
     id(...)
     ...
  }
}

**Comment by ColtonIdle** [comment]
> yes, the controller and model either must be in a different module or be in the same package of the same module. So yes, move them to the same package and let me know if that fixes the issue.

@elihart Thanks for clarifying. I actually just removed my `@AutoModel` in my kotlin classes and everything compiled again. I DO have controllers and models in different packages though and everything seems to work fine. Build speeds haven't really gotten better and now I'm starting to think it's because the controllers and models are separate. Is there a way to tell if I caused incremental kapt from working?

**Comment by elihart** [comment]
the error you reported is specific to the AutoModel processor. if you don't use that annotation you won't run into it and the package/module thing is a moot point.

Doing that wouldn't break incremental kapt. how long does your kapt task for you module take?

If you care about timings I would recommend:
- track kapt timings by adding this to your build.gradle
```
kapt {
    showProcessorTimings = true
}
```

- Enable the epoxy processor timing output via instructions in the release notes
- check in your gradle output to see whether incremental was disabled due to another annotation processor
- run you gradle build with build scan enable (--scan) and look at your scan output to see how long kapt tasks are taking

I would also temper expectations. even if incremental is working it will likely only reduce build time by about 15%

**Comment by ColtonIdle** [comment]
> the error you reported is specific to the AutoModel processor. if you don't use that annotation you won't run into it and the package/module thing is a moot point.

@elihart OOOOH. They only need to be in the same package (or different modules) only if I'm using `@Automodel`? If so then thats cool because I rather just remove the Automodel annotation.

> how long does your kapt task for you module take?

If I run `./gradlew clean` and then `./gradlew assemblePaidDebug --scan` I can see that my build took 2m 57s total build time. Looking at the scan

there are two entries that contain kapt
:app:kaptGenerateStubsPaidDebugKotlin 32.049s
:app:kaptPaidDebugKotlin 26.192s

Now I go in and add a variable to my activities onCreate (in my head this should force an incremental compilation?) if I now run `./gradlew assemblePaidDebug --scan` I can see that my build took 11s total build time (still was hoping to get this down to 1-2 seconds). Looking at the scan I see:

:app:kaptGenerateStubsPaidDebugKotlin 1.505s  
:app:kaptPaidDebugKotlinUP-TO-DATE 0.088s

> track kapt timings by adding this to your build.gradle

Already ahead of you here =) I have that enabled. After I ran a clean and then assemble I got an output of `warning: EpoxyProcessor completed in 382 ms`. Seems reasonable. On the second run (on what I consider an incremental change) I didn't see any output on timings.

@elihart lastly, I want to say that I'm not asking you to debug my build/speeds for me, I'm just still very new with all of this stuff and how it affects gradle and so I want to make sure I'm not doing anything really stupid or obviously wrong.

If everything above looks good to you then I'll keep going down the path of making my builds faster. Typically an incremental change would take about 19 seconds, so going down to 11 is still pretty awesome.

**Comment by elihart** [comment]
thanks for the details. Going from 19->11 seconds is really good and I would be happy with that. 1-2 seconds is not realistic.

When you made the incremental change you can see from `kaptPaidDebugKotlinUP-TO-DATE` that annotation processors did not run at all due to that change (which is why there were no epoxy timings outputted). So the build time is coming from something else.

Also, in the clean build `kaptPaidDebugKotlin 26.192s` is quite long. If Epoxy is only taking ~400ms then you have other annotation processors taking 25 seconds which is quite a bit.

I like seeing these numbers to sanity check Epoxy's processing performance :) as far as further improvements, if you want increased build speeds I think your best bet is to split your code into multiple modules. You could also try using the gradle build scans to analyze which tasks are taking long and try to optimize them, or use the `kapt. showProcessorTimings` setting i mentioned before to get timings for other annotation processors

**Comment by ColtonIdle** [comment]
Thanks for your help. Glad to hear that epoxy is performing up to your expectations! I'll keep digging as to the root of my issue!

**Comment by ColtonIdle** [comment]
Closing this issue as it seems that the solution was just to remove the `@AutoModel` from my kotlin models. Thanks

**Comment by ColtonIdle** [comment]
Okay... re-opening. 

Maybe I'm going crazy (staring at gradle scans all day), but I did a build, then I made a single line change (added `val name = "Colton"` to my onCreate of my Activity) and this was the output. 

So I made a single line change and a build took over 90 seconds? Of course the thing that looks suspect here is Epoxy. But maybe that's just how epoxy works? Anything seem wrong to you in this screenshot @elihart ?

<img width="1166" alt="Screen Shot 2020-05-28 at 8 10 17 PM" src="https://user-images.githubusercontent.com/31751141/83207217-9c358500-a120-11ea-8c3b-b55ffb351f5f.png">

**Comment by elihart** [comment]
The processor generated extensions file was non deterministic, since it aggregates all model classes in one file, and the order was non stable. This breaks the gradle input cache key, and forces all downstream tasks to run, even though the code is the same, the source file just has different ordering.

I've fixed that with https://github.com/airbnb/epoxy/pull/985 I believe.

I have already released an undocumented 4.0.0-beta3 version with this fix that you can try (it's what we are using internally,i just need to get around to making the official release)

**Comment by elihart** [comment]
Added release notes for beta 3 https://github.com/airbnb/epoxy/releases/tag/4.0.0-beta3

**Comment by ColtonIdle** [comment]
Thanks for confirming I wasn't going crazy! Closing for now. I'll give it a try tomorrow. Thanks @elihart

**Comment by ColtonIdle** [comment]
@elihart just confirming that everything seems to be working as expected now!
